# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AppServicePruebaJonathan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0b9436cf8cbd48d191a7bf759386e958 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1adcc94d733b482a946bfafb08d9941c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0b9436cf8cbd48d191a7bf759386e958 }}/Pag:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AppServicePruebaJonathan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_20b0ddc031c94956a5e61f14136c1737 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0b9436cf8cbd48d191a7bf759386e958 }}/Pag:${{ github.sha }}'